/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
  // Apply the Kotlin JVM plugin to add support for Kotlin on the JVM.
  id("org.jetbrains.kotlin.jvm").version("1.3.31")
  id("org.springframework.boot") version "2.1.5.RELEASE"
  id("io.spring.dependency-management") version "1.0.7.RELEASE"
  kotlin("plugin.spring") version "1.3.31"
  kotlin("kapt") version "1.3.31"
  id("io.ebean") version "11.39.1"
}

group = "com.helios.ebean"
version = "0.1"
java.sourceCompatibility = JavaVersion.VERSION_1_8

repositories {
  // Use jcenter for resolving your dependencies.
  // You can declare any Maven/Ivy/file repository here.
  mavenLocal()
  mavenCentral()
  jcenter()
}

dependencies {
  implementation("org.springframework.boot:spring-boot-starter-web")
  implementation("org.springframework.boot:spring-boot-starter-jdbc")
  implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
  implementation("org.jetbrains.kotlin:kotlin-reflect")
  implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
  implementation("io.ebean:ebean:11.39.1")
  implementation("io.ebean:ebean-querybean:11.39.1")
  implementation("io.ebean:ebean-spring-txn:11.10.4")
  implementation( "org.postgresql:postgresql:42.2.5")

  // Java 9+ support
  implementation("javax.xml.bind:jaxb-api:2.3.1")
  implementation("com.sun.xml.bind:jaxb-core:2.3.0.1")
  implementation("com.sun.xml.bind:jaxb-impl:2.3.2")
  implementation("javax.activation:activation:1.1.1")

  runtimeOnly("com.h2database:h2:1.4.197") // Fixed version as a workaround for https://github.com/h2database/h2database/issues/1841
  runtimeOnly("org.springframework.boot:spring-boot-devtools")

  kapt("org.springframework.boot:spring-boot-configuration-processor")
  kapt("io.ebean:kotlin-querybean-generator:11.39.1")

  testImplementation("org.springframework.boot:spring-boot-starter-test") {
    exclude(module = "junit")
    exclude(module = "mockito-core")
  }
  testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")
  testImplementation("org.junit.jupiter:junit-jupiter-api")
  testImplementation("com.ninja-squad:springmockk:1.1.2")
  testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine")
}


tasks.withType<KotlinCompile> {
  kotlinOptions {
    freeCompilerArgs = listOf("-Xjsr305=strict")
    jvmTarget = "1.8"
  }
}
allOpen {
  annotation("javax.persistence.Entity")
  annotation("javax.persistence.Embeddable")
  annotation("javax.persistence.MappedSuperclass")
}

tasks.withType<Test> {
  useJUnitPlatform()
}
